sonar.projectKey=fran-eliot_aula-robotica-platform
sonar.organization=fran-eliot

sonar.projectName=aula-robotica-platform
sonar.sourceEncoding=UTF-8

# Código fuente real
sonar.sources=app

# Tests
sonar.tests=tests

# Coverage
sonar.python.coverage.reportPaths=coverage.xml

# Python
sonar.python.version=3.13

# Exclusiones importantes
sonar.exclusions=\
**/.venv/**,\
**/__pycache__/**,\
**/static/**,\
**/node_modules/**,\
scripts/**,\
test.db

# Test exclusions
sonar.test.inclusions=tests/**/*.py